---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "jupyter-2"
  namespace: "default"
  labels:
    app: "jupyter"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "jupyter"
  template:
    metadata:
      labels:
        app: "jupyter"
    spec:
      volumes:
      - name: notebook-pv-storage
        persistentVolumeClaim:
          claimName: notebook-pv-claim
      containers:
      - name: "jupyter-container"
        securityContext:
          privileged: true
        image: "ubuntu:18.04"
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: "/home/notebooks"
          name: notebook-pv-storage
---
# persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: notebook-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
