---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "jupyter-vscode"
  namespace: "default"
  labels:
    app: "jupyter-vscode"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "jupyter-vscode"
  template:
    metadata:
      labels:
        app: "jupyter-vscode"
    spec:
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: pv-claim
      containers:
      - name: "jupyter-vscode"
        securityContext:
          privileged: true
        image: "gcr.io/jupyter-244404/jupyter-vscode:latest"
        lifecycle:
          postStart:
            exec:
              command: ["gcsfuse", "gcsfuse-mount-bucket", "/mnt/gcsfuse-bucket"]
          preStop:
            exec:
              command: ["fusermount", "-u", "/mnt/gcsfuse-bucket"]
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: "/home/"
          name: pv-storage
---
# persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
